# Generated by Django 6.0.3 on 2026-03-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_userName',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_highest_qualification',
            field=models.CharField(blank=True, choices=[('SSLC', 'SSLC'), ('PLUS_TWO', 'Plus Two'), ('DIPLOMA', 'Diploma'), ('UG', 'Under Graduate'), ('PG', 'Post Graduate'), ('PHD', 'PhD')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_technical_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
