# Generated by Django 6.0.3 on 2026-03-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_login', '0003_department_designation_employee_emp_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
