# Generated by Django 6.0.3 on 2026-03-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_login', '0004_remove_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
