# Generated by Django 6.0.3 on 2026-03-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_login', '0005_employee_emp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_email',
        ),
    ]
