# Generated by Django 6.0.3 on 2026-03-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_login', '0006_remove_employee_emp_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_remark',
            new_name='emp_address',
        ),
    ]
