# Generated by Django 6.0.3 on 2026-03-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_login', '0003_leaves'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
    ]
