# Generated by Django 6.0.3 on 2026-03-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_login', '0004_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
